/**
 * ssr-server.mjs — lightweight Node.js HTTP bridge for React SSR.
 *
 * Accepts POST /render with JSON body:
 *   { url: string, coverImage: string | null, initialData?: unknown }
 * Returns the server-rendered HTML string (just the #root content, not a full
 * document). Go wraps this in index.html and serves it.
 *
 * This file is copied into the Docker image alongside the Go binary.
 * The Go binary spawns it via startSSRServer() in cmd/web/main.go.
 * A circuit breaker in Go falls back to client-side rendering if this server
 * is unavailable or slow (> 1500ms).
 *
 * No Express or other HTTP framework — pure Node http module for minimal
 * cold-start overhead and no node_modules needed in production.
 *
 * The SSR bundle (dist-ssr/entry-server.js) is generated by:
 *   npm run build:ssr   (vite build --config vite.config.ssr.ts)
 * noExternal:true bundles all deps so no node_modules are needed at runtime.
 */
import http from 'node:http'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// Import the SSR bundle. Exits with code 1 if not found — the Go process
// monitors this and opens the circuit breaker (falls back to CSR).
let render
try {
  const mod = await import(join(__dirname, 'dist-ssr/entry-server.js'))
  render = mod.render
  console.log('ssr-server: entry-server loaded')
} catch (err) {
  console.error('ssr-server: failed to load entry-server.js —', err.message)
  console.error('Run `npm run build:ssr` in the frontend/ directory first.')
  process.exit(1)
}

// SSR_PORT defaults to 3010 — avoids conflicts with local dev tools.
// Must match SSR_SERVER_URL in Go (default "http://localhost:3010/render").
const PORT = parseInt(process.env.SSR_PORT ?? '3010', 10)

const server = http.createServer(async (req, res) => {
  // Only handle POST /render — anything else returns 404.
  if (req.method !== 'POST' || req.url !== '/render') {
    res.writeHead(404)
    res.end()
    return
  }

  // Accumulate the request body (JSON).
  let body = ''
  for await (const chunk of req) body += chunk

  try {
    const { url, coverImage, initialData } = JSON.parse(body)
    const html = await render(String(url), coverImage ?? null, initialData ?? null)
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' })
    res.end(html)
  } catch (err) {
    // Render errors are logged here; Go treats non-200 as SSR failure and
    // falls back to client-side rendering (no circuit breaker trip for 500).
    const msg = err instanceof Error ? err.message : String(err)
    console.error('ssr-server: render error —', msg)
    res.writeHead(500, { 'Content-Type': 'text/plain' })
    res.end(msg)
  }
})

server.listen(PORT, () => {
  console.log(`ssr-server: listening on :${PORT}`)
})
